### ISSUE TITLE
Compiling zabbix 

### ISSUE THREAD

**Issue by rohrbachger** [puzzle-it-nu/zabbix-spk#2]
I like the idea running zabbix on the synology.
Unfortunately I have a DS412, so your package wont work.

Can you share the scripts you are using to create the binaries?
Are you using a toolchain to compile or how you are doing.

Regards
Gerald

**Comment by DONCIEUX-CAMILLE** [comment]
Hi
I've done compilation for arch Cedarview which is normally your arch for DS412.
https://github.com/DONCIEUX-CAMILLE/zabbix-spk
I always have a little problem for the zabbix admin in the synology interface, but binaries are working well on my arch armada38x. I'm working on the problem...

Regards
Camille Doncieux

**Comment by rmickael62** [comment]
Apollolake architecture for a DS218+
hello, would it be possible to have the file for Apollolake architecture for a DS218 + please

**Comment by DONCIEUX-CAMILLE** [comment]
Hi
I've fixed bugs in the Zabbix Admin Control
Please have a look on
https://github.com/DONCIEUX-CAMILLE/zabbix-spk/blob/master/zabbix_cedarview-6.1_3.4.4-3.spk
Zabbix 3.4.4 version
Regards

**Comment by rohrbachger** [comment]
Hi,
I have installed your latest package, but how can I login?
I do see the control, but it says login as admin first.
What I need to do?

**Comment by DONCIEUX-CAMILLE** [comment]
Hi
This Package needs to be logged in Synology with a user which belongs to admin group.
Otherwise, I made some updates in the installer with pre-requisites added.
https://github.com/DONCIEUX-CAMILLE/zabbix-spk/blob/master/zabbix_cedarview-6.1_3.4.4-4.spk
Regards
Camille

**Comment by rohrbachger** [comment]
Camille,
I came a step forward, your new package improved the situation.
I used mariaDB 10 before, now I'using version 5.
I do see the Zabbix frontend and can login.
But the services seem not to run and Iḿ not able to start ift from the controls

I changed this php settings:
max_execution_time = 300
max_input_time = 300
always_populate_raw_data = -1
So the frontend looks okay, but still zabbix service is not running.

In the zabbix control panel I have this message:
Error in opening /usr/local/zabbix/var/zabbix_server.log
I created such a file, but this does not help.

For today I give it up, itś already late...

So if you have more tips, Iḿ pretty sure I get this running...

**Comment by DONCIEUX-CAMILLE** [comment]
Hi Gerald
Have you tried to completely desinstall the package and not just update since I think that your database is not well installed, that's why your zabbix server doesn't start.
Regards 
Camille

**Comment by rohrbachger** [comment]
Camille,

I dropped the database from commandline and reinstalled your package.
The same result.
How can I start the zabbix from commandline?
Maybe I can see there what is wrong. Which user is running zabbix?
Probably some permission issues only.

Regards
Gerald

**Comment by DONCIEUX-CAMILLE** [comment]
HI
To answer your question, to start manually the zabbix server, please try as root
/var/packages/zabbix/target/sbin/z_server_start_stop.sh start, the script has sudo for zabbix server user.

But please have a look before on your zabbix conf in 
/var/packages/zabbix/target/etc/zabbix_server.conf and verify that line 87, you have the good line ie : 
DBName=zabbix_server_synology
on line 103
DBUser=zabbix_server_rw
on line 118
DBSocket=/run/mysqld/mysqld.sock

Please verify also that your DB is well installed in your mariaDB

Thanks
Camille

**Comment by rohrbachger** [comment]
Hi,
database and the rest seems okay.  Starting as root I giving me access denied.

Looking at the script it seems to need a user : zabbixserver
I do sees this entry in passwd
zabbixserver:x:100:99:Zabbix User:/usr/local/zabbix/var:/bin/sh

looking e.g at /var/packages/zabbix/target
I do see root is owner and group.
So I think the folder rights are somehow wrong. Probably zabbixserver should be owner.
Whatever the reason was, you know I tried the installation several times.....

Uninstalling/reinstalling yesterday did not fixed this.

But maybe with this information you have a good suggestion for me.
If not I would uninstall all again, remove the zabbixserver user from the passwd and try to install again.

Regards
Gerald

**Comment by DONCIEUX-CAMILLE** [comment]
HI and thank you for your patience.
All the folders rights must be owned by root, otherwise, synology admin control will not start in the interface.
Logged as root in your putty, the 
/var/packages/zabbix/target/sbin/z_server_start_stop.sh has zabbixserver:root rights and contains sudo to start with the zabbixserver user.

Otherwise, some others simple checks :
Loggued as zabbixserver, please launch ./zabbix_server --help in /usr/local/zabbix/sbin

The result should be this :

/usr/local/zabbix/sbin$ ./zabbix_server --help
usage:
  zabbix_server [-c config-file]
  zabbix_server [-c config-file] -R runtime-option
  zabbix_server -h
  zabbix_server -V

The core daemon of Zabbix software.

Options:
  -c --config config-file        Path to the configuration file
                                 (default: "/usr/local/zabbix/etc/zabbix_server.conf")
  -f --foreground                Run Zabbix server in foreground
  -R --runtime-control runtime-option   Perform administrative functions

    Runtime control options:
      config_cache_reload        Reload configuration cache
      housekeeper_execute        Execute the housekeeper
      log_level_increase=target  Increase log level, affects all processes if
                                 target is not specified
      log_level_decrease=target  Decrease log level, affects all processes if
                                 target is not specified

      Log level control targets:
        pid                      Process identifier
        process-type             All processes of specified type (e.g., poller)
        process-type,N           Process type and number (e.g., poller,3)

  -h --help                      Display this help message
  -V --version                   Display version number

Report bugs to: <https://support.zabbix.com>
Zabbix home page: <http://www.zabbix.com>
Documentation: <https://www.zabbix.com/documentation>

**Comment by DONCIEUX-CAMILLE** [comment]
If help is not displayed, it's my fault, compilation error..
If not :
Launch directly the process in your putty as zabbixserver user
/usr/local/zabbix/sbin$ ./zabbix_server

if something is wrong, everything is logged in 
/usr/local/zabbix/var/zabbix_server.log

Regards
Camille

**Comment by rohrbachger** [comment]
Hi,
database and the rest seems okay.  Starting as root I giving me access denied.

Looking at the script it seems to need a user : zabbixserver
I do sees this entry in passwd
zabbixserver:x:100:99:Zabbix User:/usr/local/zabbix/var:/bin/sh

looking e.g at /var/packages/zabbix/target
I do see root is owner and group.
So I think the folder rights are somehow wrong. Probably zabbixserver should be owner.
Whatever the reason was, you know I tried the installation several times.....

Uninstalling/reinstalling yesterday did not fixed this.

But maybe with this information you have a good suggestion for me.
If not I would uninstall all again, remove the zabbixserver user from the passwd and try to install again.

Regards
Gerald

**Comment by rohrbachger** [comment]
Camille,

I dropped the database from commandline and reinstalled your package.
The same result.
How can I start the zabbix from commandline?
Maybe I can see there what is wrong. Which user is running zabbix?
Probably some permission issues only.

Regards
Gerald

**Comment by rohrbachger** [comment]
Camille,
you lost me at: login as zabbixserver
How can I do this?
I have tried with:
root@DiskStation:/usr/local/zabbix/var# su - zabbixserver
su: Permission denied

root@DiskStation:/usr/local/zabbix/var# sudo su - zabbixserver
su: Permission denied

The 3 users are in /etc/passwd:
zabbixserver:x:100:99:Zabbix User:/usr/local/zabbix/var:/bin/sh
zabbixproxy:x:102:99:Zabbix User:/usr/local/zabbix/var:/bin/sh
zabbixagent:x:103:99:Zabbix User:/usr/local/zabbix/var:/bin/sh

What I noticed also x right for server.enabled is not set. A difference to to agent.enabled.

root@DiskStation:/usr/local/zabbix/var# ls -l
total 8
-rwxr-xrwx 1 root root 1 Dec 22 10:16 agent.enabled
-rw-r--r-- 1 root root 1 Dec 22 10:17 server.enabled
root@DiskStation:/usr/local/zabbix/var# 

Regards
Gerald

**Comment by puzzle-it-nu** [comment]
On 22-12-2017 11:40, rohrbachger wrote:
>
> Camille,
> you lost me at: login as zabbixserver
> How can I do this?
> I have tried with:
> root@DiskStation:/usr/local/zabbix/var# su - zabbixserver
> su: Permission denied
>
> root@DiskStation:/usr/local/zabbix/var# sudo su - zabbixserver
> su: Permission denied
>
> The 3 users are in /etc/passwd:
> zabbixserver❌100:99:Zabbix User:/usr/local/zabbix/var:/bin/sh
> zabbixproxy❌102:99:Zabbix User:/usr/local/zabbix/var:/bin/sh
> zabbixagent❌103:99:Zabbix User:/usr/local/zabbix/var:/bin/sh
>
>
I have had a similar problem with a different package and had to add the 
user to /etc/shadow too.
Made a copy of the 'admin' line and changed 'admin' to the desired user.

Joop

**Comment by DONCIEUX-CAMILLE** [comment]
Thanks
I will improve the installer in the package to check that.
Regards
Camille

**Comment by rohrbachger** [comment]
Joop, Camille,
I added the users and it started working.

Thanks for your help. Without I probably would have needed ages....

Regards
Gerald
