### ISSUE TITLE
zabbix_apollolake-7.0_6.2.1-1.spk

### ISSUE THREAD

**Issue by rohrbachger** [puzzle-it-nu/zabbix-spk#21]
Iḿ trying to get already a while the package on DSM 7 running, tried already a lot but.

Blank screen on the user webFrontend
zabbix server is running, I guess the problem is somewhere in nginx.

Where I would see details from the cause?
Is there a newer version from the package available?

Regards
Gerald

**Comment by thetuxinator** [comment]
Here are packages currently working, however, also seems stalled, the main issue is that one can't open issues or contact the author on that one: https://github.com/DONCIEUX-CAMILLE/zabbix-spk
