### ISSUE TITLE
Apollolake architecture for a DS218 +

### ISSUE THREAD

**Issue by rmickael62** [puzzle-it-nu/zabbix-spk#3]
hello, would it be possible to have the file for Apollolake architecture for a DS218 + please
thank you for your work

**Comment by DONCIEUX-CAMILLE** [comment]
Hello
Yes, sure, I've yet created your toolchain env, but I need some days to finish to fix some bugs in the admin interface in the synology. Almost Done !
Normally for christmas, you will have your gift...sorry package.

**Comment by rmickael62** [comment]
Hello,
Thank you very much, it's really very nice of you, so I look forward to the arrival of Santa Claus.
Best regard.

**Comment by DONCIEUX-CAMILLE** [comment]
Merry Christmas !
Please give me feedback about every bugs you can find.
Regards

**Comment by rmickael62** [comment]
Too fast father Christmas this year a very big thank you I test it immediately.
PS: Sorry for the spelling I am french and I use a translator.
Regards

**Comment by rmickael62** [comment]
Here are the problems to meet:
Zabbix Agent => Error in opening /usr/local/zabbix/var/zabbix_agentd.log
Zabbix  Proxy => Error in opening /usr/local/zabbix/var/zabbix_proxy.log
Zabbix Server => Error in opening /usr/local/zabbix/var/zabbix_server.log
http://ip-nas/zabbix/ =>500 An error occurred while processing this request
there must be a procedure that I do not respect or I'm not good at it
Regards

**Comment by DONCIEUX-CAMILLE** [comment]
HI, I'm french too !
Normally, you have a symbolic link somewhere on your NAS at the package installation
The link /usr/local/zabbix/var to /var/packages/zabbix/target/var
please contact me directly on (replace the AT by @ in the mail)
zabbix_villadeseine AT orange.fr 
I will try to understand this evening.
Regards
